version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.504.3-lts-jdk21
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'  # ou supprimer si HTTPS non nécessaire
      - '50000:50000'
    privileged: true
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_home:
    driver: local